services:
  mysql:
    image: mysql:latest
    container_name: wp_mysql
    env_file:
      - .env  # 引用.env文件
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    networks:
      - wordpress_network

  wordpress:
    # image: wordpress:latest  # 使用官方 WordPress 镜像
    build: ./apache  # 使用当前工程目录下的apache目录下的Dockerfile
    container_name: wp_wordpress
    volumes:
      - ./wordpress_data:/var/www/html
      - ./ssl:/etc/apache2/ssl  # 挂载 SSL 证书
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wordpress_network
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_LOG_DIR: /var/log/apache2
    env_file:
      - .env  # 引用.env文件

networks:
  wordpress_network:
    driver: bridge

volumes:
  mysql_data:
  wordpress_data:
